

version: '3'

services:
  
  db:
    image: postgres
    volumes:
      - ./forcode_db:/var/lib/postgresql/data/       
    environment:   
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      
  api:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/forcode
      ports:
        - "8000:8000"
      depends_on:
        - db
  